name: Automated Error Monitoring and Alerts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  error-monitoring:
    runs-on: ubuntu-latest
    
    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
      ALERT_PHONE_NUMBER: ${{ secrets.ALERT_PHONE_NUMBER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'
          extensions: mbstring, curl, pdo_mysql

      - name: Install dependencies
        run: composer install

      - name: Run PHP Application
        run: php src/index.php || true

      - name: Check for critical error flag
        id: check_flag
        run: |
          if [ -f critical_error.flag ]; then
            echo "Critical error detected."
            echo "::set-output name=has_errors::true"
          else
            echo "No critical errors found."
            echo "::set-output name=has_errors::false"
          fi

      - name: Check for errors in error log
        run: |
          if [ -f error.log ]; then
            echo "Error log found, proceeding to parse."
            php parse_errors.php
          else
            echo "No error log found."
          fi

      - name: Send Twilio Voice Alert on Errors
        if: steps.check_flag.outputs.has_errors == 'true'
        run: php send_twilio_alert.php
